---
name: renovate-config-validator
# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - 1.2.x
      - 1.3.x
      - 1.4.x
      - 1.5.x
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@c22827f47f4f4a5364bdba19e1fe36907ef1318e # v1.1.1
